// SPDX-License-Identifier: UNLICENSED

pragma solidity ^0.8.17;

enum AdapterType {
    PANCAKESWAP_V2_ROUTER,
    PANCAKESWAP_V3_ROUTER,
    AAVE_V2_LENDING_POOL,
    Venus_vUSDC,
    Venus_vUSDT,
    AAVE_V3_LENDING_POOL,
    AAVE_V2_WRAPPED_ATOKEN,
    ABSTRACT,
    UNISWAP_V2_ROUTER,
    UNISWAP_V3_ROUTER,
    ERC4626_VAULT,
    ETH_wBETH,
    Venus
}
